name: automaticly update blogs
on: 
  push:
    branches: ["master"] # master
  pull_request:
    branches: ["master"] # master
jobs:
  build:
    runs-on: ubuntu-latest # 使用 Ubuntu 最新版虚拟机
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 拉取代码到 Runner
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 指定 Node.js 版本
 
      - name: Install dependencies
        run: |
          npm install
          npm install -g hexo-cli
 
      - name: Run build
        run: npm run build # 运行编译操作
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3 # 上传public目录内容
        with:
          path: public
    # 部署博客  
  deploy:
    needs: build   # 依赖上一个build操作
    permissions:   # # 需授予 Pages 写入权限和生成部署令牌的权限
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:         # 使用actions 部署
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4